# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4508904f834c92ffc25b544bdeb7e1fbc846bf37baeefd600568bfe82e6fb019284a59803d0ce907018bf3e0589bc49253d04dec03e4f1739306e5879585919b

test:
  secret_key_base: 7d8cb6ed839ae825a245b1d5a1002ae0fe4ab4698471c099dbc3db54f368ead93519c1a92fc6d77f4547f21257be5648f9cfe32422bd1abc25a103dffdf69486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: "abc123"
